server:
  port: 8900

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka,http://localhost:8802/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id:
        uri: lb://borrow-service
        predicates:
        - Path=/borrow/**

