server:
  port: 8900

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka,http://localhost:8802/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes: #配置路由，这里是个列表
      - id: borrow-service
        uri: lb://borrow-service
        predicates: #断言，
        - Path=/borrow/** #只要是访问这个路径，都路由到上面指定到服务地址。
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/book/**