server:
  port: 8802
spring:
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: true
  client:
    #默认为true，不需要获取服务端。
    fetch-registry: true
    #表示不需要将自己注册到eureka，多实例的可以可以开启。
    register-with-eureka: true
    service-url:
         #这里写其他服务地址即可。
      defaultZone: http://eureka01:8801/eureka
  instance:
    hostname: eureka02
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 6
