server:
  port: 8802
eureka:
  client:
    #默认为true，不需要获取服务端。
    fetch-registry: false
    #表示不需要将自己注册到eureka，多实例的可以可以开启。
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka01:8801/eureka
  instance:
    hostname: eureka02
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 6
spring:
  application:
    name: eureka-server