server:
  port: 8801
eureka:
  client:
    #默认为true，不需要获取服务端。
    fetch-registry: false
    #表示不需要将自己注册到eureka，多实例高可用时开启，默认为true。
    register-with-eureka: true
    service-url:
      #这里写其他服务地址即可。
      defaultZone: http://eureka02:8802/eureka
  instance:
    hostname: eureka01
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 6
spring:
  application:
    name: eureka-server